version: "3"
services:
  #  Create a service named pg-db.
  pg-db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name pfood_postgres. 
    container_name: "rental_postgres"
    #   Setup the username, password, and database name. 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret123
      - POSTGRES_DB=rents
    #   Maps port 54321 (localhost) to port 5432 on the container.
    ports:
      - "54321:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    volumes:
      - /var/lib/postgresql/data